//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_SERVICIO
    {
        public int IDDETALLE { get; set; }
        public int IDCIERRE { get; set; }
        public Nullable<int> DIAS { get; set; }
        public Nullable<int> IDORDENSERVICIO { get; set; }
        public string CODIGOORDENSERVICIO { get; set; }
        public Nullable<int> IDLOCAL { get; set; }
        public string LOCAL { get; set; }
        public string IDTIPOSERVICIO { get; set; }
        public string TIPOSERVICIO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string TIPO_CAFE { get; set; }
        public Nullable<int> INICIOSACO { get; set; }
        public Nullable<decimal> INICIOTARA { get; set; }
        public Nullable<decimal> INICIOKGBRUTO { get; set; }
        public Nullable<decimal> INICIOKGNETO { get; set; }
        public Nullable<int> FINSACO { get; set; }
        public Nullable<decimal> FINTARA { get; set; }
        public Nullable<decimal> FINKGBRUTO { get; set; }
        public Nullable<decimal> FINKGNETO { get; set; }
        public string CERTIFICADO { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> USUARIOREGISTRO { get; set; }
        public string VUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string OBSERVACION { get; set; }
        public string CodigoLiquidacion { get; set; }
        public string CodigoTraslado { get; set; }
    }
}
