//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_CONTRATO
    {
        public int IDDETALLE { get; set; }
        public int IDCIERRE { get; set; }
        public Nullable<int> IDCONTRATO { get; set; }
        public string IDCONTRATOCOMPRA { get; set; }
        public Nullable<int> IDLOCAL { get; set; }
        public string LOCAL { get; set; }
        public Nullable<int> IDTIPOPRECIO { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string TIPOCOMPRA { get; set; }
        public Nullable<int> COSECHA { get; set; }
        public string FECHACONTRATO { get; set; }
        public string TIPOCAFE { get; set; }
        public Nullable<decimal> KGCONTRATO { get; set; }
        public Nullable<int> SACOCONTRATO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string CALIDAD { get; set; }
        public Nullable<int> IDRENDIMIENTO { get; set; }
        public Nullable<int> IDDEFECTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CERTIFICACION { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<decimal> KGBASE { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> FIJACION { get; set; }
        public string MES_FIJACION { get; set; }
        public string DIFERENCIAL { get; set; }
        public Nullable<decimal> KGLIQUIDADO { get; set; }
    }
}
