//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_LIQUIDACION
    {
        public int IDDETALLE { get; set; }
        public int IDCIERRE { get; set; }
        public Nullable<int> IdLiquidacion { get; set; }
        public Nullable<int> IdLocal { get; set; }
        public string CodigoLiquidacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<int> IdContactoCliente { get; set; }
        public string PRODUCTOR { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public string IdGuiaIngreso { get; set; }
        public string DescGuiaIngreso { get; set; }
        public Nullable<int> IdContratoCompra { get; set; }
        public string DescContratoCompra { get; set; }
        public Nullable<decimal> TotalSacoGi { get; set; }
        public Nullable<decimal> TotalKgNetoGi { get; set; }
        public Nullable<decimal> TotalSacoCc { get; set; }
        public Nullable<decimal> TotalKgNetoCc { get; set; }
        public Nullable<decimal> DiferenciaSaco { get; set; }
        public Nullable<decimal> DiferenciaKg { get; set; }
        public string CALIDAD { get; set; }
        public Nullable<int> IDTIPORENDIMIENTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> KGLIQUIDADO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> KGBASE { get; set; }
        public Nullable<decimal> PRECIOVENTA { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdEstado2 { get; set; }
        public string FacturaSerie { get; set; }
        public string FacturaNumero { get; set; }
        public string FacturaFecha { get; set; }
        public string SerieDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string CERTIFICACION { get; set; }
        public string USUARIOASIGNACIONPRECIO { get; set; }
        public Nullable<System.DateTime> FECHAASIGNACIONPRECIO { get; set; }
    }
}
