//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_GARANTIA
    {
        public int IdGarantia { get; set; }
        public int IdCliente { get; set; }
        public int IdRegion { get; set; }
        public int IdMoneda { get; set; }
        public decimal MontoGarantia { get; set; }
        public string NroPartida { get; set; }
        public int IdMonedaTasacion { get; set; }
        public decimal MontoTasacion { get; set; }
        public int IdTipoInmueble { get; set; }
        public System.DateTime FechaHipoteca { get; set; }
        public int IdSituacionHipoteca { get; set; }
        public Nullable<decimal> CoordenadaX { get; set; }
        public Nullable<decimal> CoordenadaY { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdTituloValor { get; set; }
        public Nullable<int> IdTipoGarantia { get; set; }
        public string DireccionGarantia { get; set; }
    }
}
