//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    
    public partial class ComprobanteVentaFilePorId
    {
        public int IdComprobante { get; set; }
        public string IdTipoComprobante { get; set; }
        public string TipoComprobante { get; set; }
        public string NroComprobante { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> IdTipoDocumentoCliente { get; set; }
        public string NroDocumentoCliente { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> ImporteSubtotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public int IdDetalleComprobante { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string DescripcionServicio { get; set; }
        public string DenominacionTipoDoc { get; set; }
        public string CorrelativoDocRef { get; set; }
        public string MotivoDescripcion { get; set; }
        public string Observacion { get; set; }
        public string FechaRegistra { get; set; }
        public string IdTipoOperacion { get; set; }
        public string IdTipoImpuesto { get; set; }
        public string IdSerieComprobante { get; set; }
        public Nullable<decimal> ExpPrecioUnitarioKilo { get; set; }
        public string TipoDiscrepancia { get; set; }
    }
}
