//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTEVENTA_PROCESO
    {
        public int IdProcesoComprobante { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public Nullable<int> IdEstadoProceso { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
