//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTEVENTA_FILE
    {
        public int IdComprobanteFile { get; set; }
        public int IdComprobante { get; set; }
        public string Correlativo { get; set; }
        public string TipoComprobante { get; set; }
        public string NombreArhivo { get; set; }
        public string SignatureValue { get; set; }
        public string DigestValue { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public string StateInvoice { get; set; }
        public string Trama { get; set; }
    }
}
