//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTEVENTA_APROBACION
    {
        public int IdAprobacion { get; set; }
        public Nullable<int> IdUsuarioRegistra { get; set; }
        public Nullable<int> IdUsuarioAprueba { get; set; }
        public string IdLocal { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
