//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    
    public partial class ComprobanteVenta
    {
        public Nullable<long> ROWNUMBER { get; set; }
        public string RAZONSOCIAL_PRODELSUR { get; set; }
        public string RUC_PRODELSUR { get; set; }
        public string DIRECCION_PRODELSUR { get; set; }
        public int IDCOMPROBANTE { get; set; }
        public string IdTipoComprobante { get; set; }
        public string TIPOCOMPROBANTE { get; set; }
        public string NROCOMPROBANTE { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string DIRECCIONCLIENTE { get; set; }
        public string TIPODOCUMENTOCLIENTE { get; set; }
        public string NRODOCUMENTOCLIENTE { get; set; }
        public string FECHAOPERACION { get; set; }
        public string FECHAOPERACIONUNO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string PRECIOUNITARIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string TIPOSERVICIO { get; set; }
        public Nullable<decimal> IMPORTESUBTOTAL { get; set; }
        public Nullable<decimal> IMPUESTO { get; set; }
        public Nullable<decimal> IMPORTETOTAL { get; set; }
        public string USUARIO { get; set; }
        public string DESCRIPCIONSERVICIO { get; set; }
        public int CODIGOUNIDAD { get; set; }
        public string UNIDAD { get; set; }
        public string GUIAREMISIONREF { get; set; }
        public string CodigoHash { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public string DenominacionDesc { get; set; }
        public string CorrelativoDocRef { get; set; }
        public string FechaDocRef { get; set; }
        public string MotivoNotaDebito { get; set; }
        public string PuertoEmbarque { get; set; }
        public string PuertoDestino { get; set; }
        public string ExpVapor { get; set; }
        public string ExpFormaPago { get; set; }
        public string ExpFlete { get; set; }
        public string ExpSeguro { get; set; }
        public string ExpNotificar { get; set; }
        public string ExpPaisOrigen { get; set; }
        public string ExpOtrosConceptos { get; set; }
        public string IdTipoOperacion { get; set; }
        public string ContratoReferencia { get; set; }
        public Nullable<decimal> ExpCantidadComercial { get; set; }
        public Nullable<decimal> ExpNetWeight { get; set; }
        public Nullable<decimal> ExpTara { get; set; }
        public Nullable<decimal> ExpGrossWeight { get; set; }
        public string ExpMarks { get; set; }
        public string ExpPartidaArancelaria { get; set; }
        public Nullable<decimal> ExpFairTrade { get; set; }
        public Nullable<decimal> ExpImporte { get; set; }
        public Nullable<decimal> ExpPrecioFairTrade { get; set; }
        public Nullable<decimal> ExpPrecioUnitario { get; set; }
        public string ExpMedida { get; set; }
        public Nullable<int> ExpMedidaCantidad { get; set; }
        public string Observaciones { get; set; }
        public string IdTipoImpuesto { get; set; }
        public string IdSerieComprobante { get; set; }
        public string OperacionName { get; set; }
        public string NombreImgBarCode { get; set; }
    }
}
