//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_COMPRA
    {
        public int IdContrato { get; set; }
        public int IdLocal { get; set; }
        public string SerieContrato { get; set; }
        public string NumContrato { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public int IdTipoCafe { get; set; }
        public int IdTipoCompra { get; set; }
        public int Cosecha { get; set; }
        public decimal Cantidad { get; set; }
        public int IdTipoUnidadMedida { get; set; }
        public decimal PesoxSacoRecibido { get; set; }
        public decimal PesoSaco { get; set; }
        public decimal TotalPesoSaco { get; set; }
        public int IdCliente { get; set; }
        public int IdCalidad { get; set; }
        public int IdTipoHumedad { get; set; }
        public int IdTipoRendimiento { get; set; }
        public decimal PrecioTabla { get; set; }
        public Nullable<int> ChkPrecioNuevo { get; set; }
        public Nullable<decimal> PrecioNuevo { get; set; }
        public Nullable<int> IdTrader { get; set; }
        public string IdCertificadoVSP { get; set; }
        public string DescCertificacion { get; set; }
        public Nullable<int> IdTipoPrecio { get; set; }
        public Nullable<System.DateTime> FechaEntregaInicio { get; set; }
        public Nullable<System.DateTime> FechaEntregaFin { get; set; }
        public int PorAutorizar { get; set; }
        public Nullable<int> UsuarioRegistroGeneral { get; set; }
        public Nullable<System.DateTime> FechaRegistroGeneral { get; set; }
        public Nullable<int> UsuarioModificaGeneral { get; set; }
        public Nullable<System.DateTime> FechaModificaGeneral { get; set; }
        public string Observacion { get; set; }
        public string ObservacionInterna { get; set; }
        public Nullable<int> IdAgente { get; set; }
        public string ReferenciaAgente { get; set; }
        public Nullable<int> ImprimeReferencia { get; set; }
        public Nullable<decimal> ComisionMonto { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> ComisionCantidad { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> UsuarioRegistroComentario { get; set; }
        public Nullable<System.DateTime> FechaRegistroComentario { get; set; }
        public Nullable<int> UsuarioModificaComentario { get; set; }
        public Nullable<System.DateTime> FechaModificaComentario { get; set; }
        public string InstruccionMuestra { get; set; }
        public Nullable<int> IdTipoDsa { get; set; }
        public Nullable<int> IdTipoTerminoEntrega { get; set; }
        public Nullable<int> IdTipoReglasPeso { get; set; }
        public Nullable<int> IdTipoCondPago { get; set; }
        public Nullable<int> IdTipoControlBase { get; set; }
        public Nullable<int> IdTipoArbitraje { get; set; }
        public Nullable<int> IdTipoDestino { get; set; }
        public Nullable<int> IdSaco { get; set; }
        public string IdTipoFijador { get; set; }
        public Nullable<int> UsuarioRegistroTerminos { get; set; }
        public Nullable<System.DateTime> FechaRegistroTerminos { get; set; }
        public Nullable<int> UsuarioModificaTerminos { get; set; }
        public Nullable<System.DateTime> FechaModificaTerminos { get; set; }
        public Nullable<int> IdTipoCambioOperacion { get; set; }
        public Nullable<decimal> PrecioOutFijado { get; set; }
        public Nullable<int> IdOutTipoMoneda { get; set; }
        public Nullable<decimal> PrecioOutCantidad { get; set; }
        public Nullable<int> IdOutUnidadMedida { get; set; }
        public Nullable<decimal> PrecioOutMercado { get; set; }
        public Nullable<decimal> DiferencialBaseOut { get; set; }
        public Nullable<decimal> PrecioFinalSoles { get; set; }
        public Nullable<decimal> PrecioFinalDolares { get; set; }
        public Nullable<int> UsuarioRegistroOut { get; set; }
        public Nullable<System.DateTime> FechaRegistroOut { get; set; }
        public Nullable<int> UsuarioModificaOut { get; set; }
        public Nullable<System.DateTime> FechaModificaOut { get; set; }
        public Nullable<int> UnfxPendienteFijar { get; set; }
        public Nullable<int> UnfxMesFijacion { get; set; }
        public Nullable<decimal> UnfxDiferencial { get; set; }
        public Nullable<int> UnfxTipoDiferencial { get; set; }
        public string UnfxTipoFijador { get; set; }
        public Nullable<System.DateTime> UnfxFechaExpiraFijacion { get; set; }
        public Nullable<decimal> UnfxPrecioFinalSoles { get; set; }
        public Nullable<decimal> UnfxPrecioFinalDolares { get; set; }
        public Nullable<int> UnfxUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> UnfxFechaRegistro { get; set; }
        public Nullable<int> UnfxUsuarioModifica { get; set; }
        public Nullable<System.DateTime> UnfxFechaModifica { get; set; }
        public Nullable<decimal> OpenDiferencial { get; set; }
        public Nullable<System.DateTime> OpenFechaDiferencial { get; set; }
        public int IdEstado { get; set; }
        public int ChkLiquidacion { get; set; }
        public string GiExcel { get; set; }
    }
}
