//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_ZONA_SWITCH
    {
        public int IdDetalleSwitch { get; set; }
        public int IdContrato { get; set; }
        public decimal Diferencial { get; set; }
        public int IdTipoDiferencial { get; set; }
        public int IdMesFijacion { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdEstado { get; set; }
        public Nullable<decimal> CostoSwitch { get; set; }
    }
}
