//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_COMPRA_UNFIXED
    {
        public int IdContratoUnFix { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<System.DateTime> FechaFijacion { get; set; }
        public Nullable<int> Sacos { get; set; }
        public Nullable<int> IdMesFijacion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioSoles { get; set; }
        public int IdEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
