//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_COMPRA_SWITCH
    {
        public int IdSwitch { get; set; }
        public int IdContrato { get; set; }
        public int IdFijacionActual { get; set; }
        public decimal DiferencialActual { get; set; }
        public int IdTipoDiferencialActual { get; set; }
        public int IdFijacionNuevo { get; set; }
        public decimal DiferencialNuevo { get; set; }
        public int IdTipoDiferencialNuevo { get; set; }
        public int Cantidad { get; set; }
        public int IdEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
