//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        public string IdEmpresa { get; set; }
        public string IdLocal { get; set; }
        public string IdEstacion { get; set; }
        public string vDescripcion { get; set; }
        public int nEstado { get; set; }
        public int nIdUsuarioMod { get; set; }
        public System.DateTime dFechaMod { get; set; }
    }
}
