//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JefaturaCorreo
    {
        public decimal IdCorreo { get; set; }
        public string vIdJefatura { get; set; }
        public int nIdUsuario { get; set; }
        public string vTipo { get; set; }
    }
}
