//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABORATORIO
    {
        public int IdLaboratorio { get; set; }
        public int IdLaboratorioZona { get; set; }
        public int IdCliente { get; set; }
        public int IdDocOperacion { get; set; }
        public int IdDocumento { get; set; }
        public string IdLocal { get; set; }
        public int IdTipoCafe { get; set; }
        public System.DateTime FechaAnalisis { get; set; }
        public string FormatoAnalisis { get; set; }
        public int NroSaco { get; set; }
        public decimal KgBruto { get; set; }
        public decimal KgNeto { get; set; }
        public decimal PesoSaco { get; set; }
        public decimal Tara { get; set; }
        public Nullable<decimal> HumedadZona { get; set; }
        public Nullable<decimal> PorcRendimiento { get; set; }
        public string Calidad { get; set; }
        public Nullable<decimal> APPorcHumedad { get; set; }
        public Nullable<decimal> APPorcAgua { get; set; }
        public Nullable<decimal> APMHumedad { get; set; }
        public Nullable<decimal> APPorcPajilla { get; set; }
        public Nullable<decimal> APMSeca { get; set; }
        public Nullable<decimal> APPtc { get; set; }
        public Nullable<decimal> APPorcCompra { get; set; }
        public Nullable<decimal> APOro { get; set; }
        public Nullable<decimal> APPorcOro { get; set; }
        public Nullable<decimal> APColor { get; set; }
        public Nullable<decimal> APPorcColor { get; set; }
        public Nullable<decimal> APMaquina { get; set; }
        public Nullable<decimal> APPorcMaquina { get; set; }
        public Nullable<decimal> APBanda { get; set; }
        public Nullable<decimal> APPorcBanda { get; set; }
        public Nullable<decimal> APBola { get; set; }
        public Nullable<decimal> APPorcBola { get; set; }
        public Nullable<decimal> APOtros { get; set; }
        public Nullable<decimal> APProcOtros { get; set; }
        public Nullable<decimal> APSc18 { get; set; }
        public Nullable<decimal> APPorcSc18 { get; set; }
        public Nullable<decimal> APSc16 { get; set; }
        public Nullable<decimal> APPorcSc16 { get; set; }
        public Nullable<decimal> APSc12 { get; set; }
        public Nullable<decimal> APPorcSc12 { get; set; }
        public Nullable<decimal> APSc0 { get; set; }
        public Nullable<decimal> APPorcSc0 { get; set; }
        public string APAcidez { get; set; }
        public string APCuerpo { get; set; }
        public string APCalidad { get; set; }
        public Nullable<int> AOTrilla { get; set; }
        public Nullable<int> AOLote { get; set; }
        public string AORuma { get; set; }
        public Nullable<decimal> AOBrocado { get; set; }
        public Nullable<decimal> AOBanda { get; set; }
        public Nullable<decimal> AOManchado { get; set; }
        public Nullable<decimal> AOColor { get; set; }
        public Nullable<decimal> AOInmaduro { get; set; }
        public Nullable<decimal> AOMaquina { get; set; }
        public Nullable<decimal> AOMantequilla { get; set; }
        public Nullable<decimal> AOBlanco { get; set; }
        public Nullable<decimal> AOProcHumedad { get; set; }
        public Nullable<decimal> AODeforme { get; set; }
        public Nullable<decimal> AOPartido { get; set; }
        public Nullable<decimal> AOOtros { get; set; }
        public int NroTaza { get; set; }
        public string Observacion { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<decimal> PorcTamoCascara { get; set; }
        public Nullable<decimal> PorcDescarte { get; set; }
        public string IdCertificacion { get; set; }
        public string vcCertificacion { get; set; }
    }
}
