//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public string idLocal { get; set; }
        public string vDescripcion { get; set; }
        public string vDireccion { get; set; }
        public string IdEmpresa { get; set; }
        public Nullable<int> nEstado { get; set; }
        public string IdUbigeo { get; set; }
        public string idLocalSGA { get; set; }
        public string idLocalGrupoSam { get; set; }
        public string idLocalConta { get; set; }
        public Nullable<int> nTipoLocal { get; set; }
        public string Ruta_DBF_Canjes { get; set; }
        public string IdLocalSAP { get; set; }
        public string vAliasLocalSAP { get; set; }
        public string vRuta_DBF_Casino { get; set; }
        public string vRuta_Movimiento_Casino { get; set; }
        public string idLocalExistencia_SGA { get; set; }
        public string vNombre_DBF_Casino { get; set; }
        public string IdLocalSAPStock { get; set; }
        public string vRuta_Sorteo_Casino { get; set; }
    }
}
