//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string IdMenu { get; set; }
        public int IdSistema { get; set; }
        public string idMenuPadre { get; set; }
        public string vDescripcion { get; set; }
        public string vNombreFormulario { get; set; }
        public Nullable<int> nEstado { get; set; }
    }
}
