//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO_COMPARTIDO_USUARIO
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string vcModulo { get; set; }
        public string vcMenu { get; set; }
        public Nullable<int> InEstado { get; set; }
        public Nullable<System.DateTime> dtReg { get; set; }
    }
}
