//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODCS_ESTADOS
    {
        public int IdEstadoProceso { get; set; }
        public int inTipoEstado { get; set; }
        public string vcEstadoProceso { get; set; }
        public int inEstado { get; set; }
    }
}
