//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODCS_PROVEEDOR
    {
        public int IdProveedor { get; set; }
        public int IdTipoProveedor { get; set; }
        public string vcDocIdentidad { get; set; }
        public string vcNombreComercial { get; set; }
        public string vcRazonSocial { get; set; }
        public string vcNombreCliente { get; set; }
        public string vcApellidoCliente { get; set; }
        public string vcTelefonoPrincipal { get; set; }
        public int IdDepartamento { get; set; }
        public int IdProvincia { get; set; }
        public int IdDistrito { get; set; }
        public string vcDireccion { get; set; }
        public int InEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
