//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA_CAB
    {
        public int IdOrden { get; set; }
        public int IdOrdenInterno { get; set; }
        public int IdSolicitante { get; set; }
        public int IdProveedor { get; set; }
        public int IdClienteBanco { get; set; }
        public int IdCentroCosto { get; set; }
        public int IdTipoOrden { get; set; }
        public int IdOperacion { get; set; }
        public int IdSubTipoOperacion { get; set; }
        public string vcSerieCotizacion { get; set; }
        public string vcTelefono { get; set; }
        public int IdLocal { get; set; }
        public string TipoMoneda { get; set; }
        public int inTipoCompraServicio { get; set; }
        public string vcCompraServicio { get; set; }
        public int inTipoGastoPlanta { get; set; }
        public string vcGastoPlanta { get; set; }
        public decimal dcSubTotal { get; set; }
        public decimal dcIGVvalor { get; set; }
        public decimal dcIgv { get; set; }
        public decimal dcValorTotal { get; set; }
        public int inEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdEstadoProceso { get; set; }
        public Nullable<int> IdUsuarioProceso { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string vcMotivo { get; set; }
    }
}
