//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTORGADO_ZONA_BK
    {
        public int IdOtorgado { get; set; }
        public int IdOtorgadoZona { get; set; }
        public int IdLocal { get; set; }
        public int IdCliente { get; set; }
        public int IdContactoCliente { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string IdTipoIngreso { get; set; }
        public int IdTipoModalidadOtorgado { get; set; }
        public string DocumentoReferencia { get; set; }
        public Nullable<int> IdTipoCajaChica { get; set; }
        public int IdMoneda { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> TC { get; set; }
        public int ChkDiferenteMoneda { get; set; }
        public Nullable<decimal> MontoPagar { get; set; }
        public int IdTipoMotivoOtorgado { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string NroOperacion { get; set; }
        public Nullable<System.DateTime> FechaTransferencia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public string DescCuentaBancaria { get; set; }
        public string IdAprobacion { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioAnula { get; set; }
        public Nullable<System.DateTime> FechaAnula { get; set; }
        public Nullable<int> UsuarioAprobacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> cosecha { get; set; }
    }
}
