//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO
    {
        public int IdParametro { get; set; }
        public string TipoParametro { get; set; }
        public string Descripcion { get; set; }
        public string Clave { get; set; }
        public string Clave1 { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string Clave2 { get; set; }
    }
}
