//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitsConnection
    {
        public int IdPermitsConnection { get; set; }
        public string vNombre { get; set; }
        public string vObservacion { get; set; }
        public Nullable<int> nEstado { get; set; }
    }
}
