//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIO_DIA
    {
        public int IdPrecioDia { get; set; }
        public int IdLocal { get; set; }
        public int IdMoneda { get; set; }
        public decimal KgBase { get; set; }
        public System.DateTime FechaPrecio { get; set; }
        public int Defecto { get; set; }
        public int IdTipoCalidadPrecio { get; set; }
        public int IdCertificado { get; set; }
        public decimal Precio { get; set; }
        public int IdEstadoDiario { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
