//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_PRP_CABECERA_BK
    {
        public int IdOrdenServicio { get; set; }
        public int IdOrdenServicioInterno { get; set; }
        public string IdLocal { get; set; }
        public string IdTipoServicio { get; set; }
        public int IdTipoCafe { get; set; }
        public int Cosecha { get; set; }
        public int IdCliente { get; set; }
        public int InicioSaco { get; set; }
        public decimal InicioTara { get; set; }
        public decimal InicioKgBruto { get; set; }
        public decimal InicioKgNeto { get; set; }
        public Nullable<int> FinTipoSaco { get; set; }
        public Nullable<int> FinSaco { get; set; }
        public Nullable<decimal> FinTara { get; set; }
        public Nullable<decimal> FinKgBruto { get; set; }
        public Nullable<decimal> FinKgNeto { get; set; }
        public string Observacion { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioFinProceso { get; set; }
        public Nullable<System.DateTime> FechaFinProceso { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string TipoServicioDescripcion { get; set; }
    }
}
