//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_PRP_ELIMINADO
    {
        public int IdResultado { get; set; }
        public Nullable<int> IdOrdenServicio { get; set; }
        public Nullable<int> IdTipoOperacion { get; set; }
        public Nullable<int> IdCalidad { get; set; }
        public Nullable<decimal> Rendimiento { get; set; }
        public Nullable<int> IdTipoCafe { get; set; }
        public Nullable<int> IdTipoSaco { get; set; }
        public Nullable<int> NroSaco { get; set; }
        public Nullable<decimal> KgBruto { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public Nullable<decimal> KgNeto { get; set; }
        public Nullable<int> IdGuiaIngreso { get; set; }
        public Nullable<int> Lote { get; set; }
    }
}
