//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_VISITA
    {
        public string IdSolicitud { get; set; }
        public string RazonSocial { get; set; }
        public string NombreVisita { get; set; }
        public string ApellidoVisita { get; set; }
        public string NumDocumento { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
        public Nullable<int> IdMotivoVisita { get; set; }
        public Nullable<int> IdTipoVisita { get; set; }
        public string NumPlaca { get; set; }
        public string NumTracto { get; set; }
        public string NumContenedor { get; set; }
        public string NombreChofer { get; set; }
        public string ApellidoChofer { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> UsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> UsuarioSalida { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual MOTIVO_VISITA MOTIVO_VISITA { get; set; }
        public virtual TIPO_VISITA TIPO_VISITA { get; set; }
    }
}
