//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG
    {
        public int id { get; set; }
        public string vcException { get; set; }
        public System.DateTime dtFecReg { get; set; }
        public int idUsuario { get; set; }
    }
}
