//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO_CARGAMASIVA
    {
        public int id { get; set; }
        public string vcNombreArchivo { get; set; }
        public string vcRuta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> dtFechaRegistro { get; set; }
    }
}
