//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_VISITA
    {
        public int IdTipoVisita { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Placa { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
