//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppTest.ServiceRuc2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.insite.pe/test.ruc1.php?wsdl", ConfigurationName="ServiceRuc2.ServiceRUCPortType")]
    public interface ServiceRUCPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.insite.pe/test.ruc1.php/consultaRUC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string consultaRUC(string ruc, string username, string hash, string tracking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.insite.pe/test.ruc1.php/consultaRUC", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> consultaRUCAsync(string ruc, string username, string hash, string tracking);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceRUCPortTypeChannel : ConsoleAppTest.ServiceRuc2.ServiceRUCPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRUCPortTypeClient : System.ServiceModel.ClientBase<ConsoleAppTest.ServiceRuc2.ServiceRUCPortType>, ConsoleAppTest.ServiceRuc2.ServiceRUCPortType {
        
        public ServiceRUCPortTypeClient() {
        }
        
        public ServiceRUCPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRUCPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRUCPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRUCPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string consultaRUC(string ruc, string username, string hash, string tracking) {
            return base.Channel.consultaRUC(ruc, username, hash, tracking);
        }
        
        public System.Threading.Tasks.Task<string> consultaRUCAsync(string ruc, string username, string hash, string tracking) {
            return base.Channel.consultaRUCAsync(ruc, username, hash, tracking);
        }
    }
}
