//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppTest.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bCambioPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dFecha_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nIdUsuario_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vApeMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vApePatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vCodTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vIdJefaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bCambioPassword {
            get {
                return this.bCambioPasswordField;
            }
            set {
                if ((this.bCambioPasswordField.Equals(value) != true)) {
                    this.bCambioPasswordField = value;
                    this.RaisePropertyChanged("bCambioPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dFecha_Mod {
            get {
                return this.dFecha_ModField;
            }
            set {
                if ((this.dFecha_ModField.Equals(value) != true)) {
                    this.dFecha_ModField = value;
                    this.RaisePropertyChanged("dFecha_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nEstado {
            get {
                return this.nEstadoField;
            }
            set {
                if ((this.nEstadoField.Equals(value) != true)) {
                    this.nEstadoField = value;
                    this.RaisePropertyChanged("nEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nIdUsuario_Mod {
            get {
                return this.nIdUsuario_ModField;
            }
            set {
                if ((this.nIdUsuario_ModField.Equals(value) != true)) {
                    this.nIdUsuario_ModField = value;
                    this.RaisePropertyChanged("nIdUsuario_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vApeMat {
            get {
                return this.vApeMatField;
            }
            set {
                if ((object.ReferenceEquals(this.vApeMatField, value) != true)) {
                    this.vApeMatField = value;
                    this.RaisePropertyChanged("vApeMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vApePat {
            get {
                return this.vApePatField;
            }
            set {
                if ((object.ReferenceEquals(this.vApePatField, value) != true)) {
                    this.vApePatField = value;
                    this.RaisePropertyChanged("vApePat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vCodTrabajador {
            get {
                return this.vCodTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.vCodTrabajadorField, value) != true)) {
                    this.vCodTrabajadorField = value;
                    this.RaisePropertyChanged("vCodTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vCorreo {
            get {
                return this.vCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.vCorreoField, value) != true)) {
                    this.vCorreoField = value;
                    this.RaisePropertyChanged("vCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vIdJefatura {
            get {
                return this.vIdJefaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.vIdJefaturaField, value) != true)) {
                    this.vIdJefaturaField = value;
                    this.RaisePropertyChanged("vIdJefatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombre {
            get {
                return this.vNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vNombreField, value) != true)) {
                    this.vNombreField = value;
                    this.RaisePropertyChanged("vNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vPassword {
            get {
                return this.vPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.vPasswordField, value) != true)) {
                    this.vPasswordField = value;
                    this.RaisePropertyChanged("vPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vUsuario {
            get {
                return this.vUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vUsuarioField, value) != true)) {
                    this.vUsuarioField = value;
                    this.RaisePropertyChanged("vUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Validar_Usuario", ReplyAction="http://tempuri.org/IUsuarioService/Validar_UsuarioResponse")]
        ConsoleAppTest.ServiceUsuario.Usuario[] Validar_Usuario(ConsoleAppTest.ServiceUsuario.Usuario oU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Validar_Usuario", ReplyAction="http://tempuri.org/IUsuarioService/Validar_UsuarioResponse")]
        System.Threading.Tasks.Task<ConsoleAppTest.ServiceUsuario.Usuario[]> Validar_UsuarioAsync(ConsoleAppTest.ServiceUsuario.Usuario oU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetValidarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/GetValidarUsuarioResponse")]
        ConsoleAppTest.ServiceUsuario.Usuario GetValidarUsuario(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetValidarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/GetValidarUsuarioResponse")]
        System.Threading.Tasks.Task<ConsoleAppTest.ServiceUsuario.Usuario> GetValidarUsuarioAsync(string user, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : ConsoleAppTest.ServiceUsuario.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<ConsoleAppTest.ServiceUsuario.IUsuarioService>, ConsoleAppTest.ServiceUsuario.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppTest.ServiceUsuario.Usuario[] Validar_Usuario(ConsoleAppTest.ServiceUsuario.Usuario oU) {
            return base.Channel.Validar_Usuario(oU);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppTest.ServiceUsuario.Usuario[]> Validar_UsuarioAsync(ConsoleAppTest.ServiceUsuario.Usuario oU) {
            return base.Channel.Validar_UsuarioAsync(oU);
        }
        
        public ConsoleAppTest.ServiceUsuario.Usuario GetValidarUsuario(string user, string password) {
            return base.Channel.GetValidarUsuario(user, password);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppTest.ServiceUsuario.Usuario> GetValidarUsuarioAsync(string user, string password) {
            return base.Channel.GetValidarUsuarioAsync(user, password);
        }
    }
}
