//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJACHICA
    {
        public int IdCajaChica { get; set; }
        public int IdCajaChicaInterno { get; set; }
        public int IdLocal { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public Nullable<int> IdCatalogoCuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> MontoMinimo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoMaximo { get; set; }
        public string IdMoneda { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
    }
}
