//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJACHICA_SALDO
    {
        public int IdCajaChicaSaldo { get; set; }
        public decimal MontoInicial { get; set; }
        public decimal MontoOperacion { get; set; }
        public decimal Saldo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> Vigente { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public int IdCajaChica { get; set; }
        public Nullable<int> IdGasto_PRP { get; set; }
        public Nullable<int> IdMovilidadCab { get; set; }
        public Nullable<int> IdCajaChicaSaldoRef { get; set; }
        public Nullable<long> Tick { get; set; }
    }
}
