//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJACHICA_CIERRE
    {
        public int IdCajaChicaCierre { get; set; }
        public int IdGastoMovilidadPRP { get; set; }
        public int IdCajaChica { get; set; }
        public Nullable<int> IdTipoGasto { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> Cierre { get; set; }
        public Nullable<long> Tick { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
    }
}
