//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJACHICA_TIPODOCUMENTO
    {
        public int IdCajaChicaTipoDocumento { get; set; }
        public Nullable<int> IdSubTipo { get; set; }
        public string TipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
