//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOGO_CUENTA_CONTABLE
    {
        public int IdCatalogoCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string CuentaContableDescripcion { get; set; }
        public string CuentaHyperion { get; set; }
        public string CuentaHyperionDescripcion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> TipoOperacion { get; set; }
    }
}
