//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBANCO_TRABAJADOR
    {
        public int IdCuentaBancoTrabajador { get; set; }
        public string NroCuentaCheque { get; set; }
        public string CodigoInterbancario { get; set; }
        public Nullable<int> TipoTransaccion { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
