//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO_SALDO
    {
        public int IdCertificadoSaldo { get; set; }
        public int IdGuia { get; set; }
        public int IdCertificado { get; set; }
        public int IdCliente { get; set; }
        public int Cosecha { get; set; }
        public decimal Tope { get; set; }
        public decimal Operacion { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<int> IdSello { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string IdTipoOperacion { get; set; }
        public Nullable<int> idCargar { get; set; }
    }
}
