//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO_SALDO_HISTORY
    {
        public int IdCertificadoSaldoHistory { get; set; }
        public int IdCertificadoSaldo { get; set; }
        public decimal Saldo { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaRegistroRef { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
    }
}
