//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_OTORGADO
    {
        public int IDDETALLE { get; set; }
        public int IDCIERRE { get; set; }
        public Nullable<int> IdOtorgado { get; set; }
        public Nullable<int> IdOtorgadoZona { get; set; }
        public string CodigoOtorgadoZona { get; set; }
        public Nullable<int> IdLocal { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdContactoCliente { get; set; }
        public string CLIENTE { get; set; }
        public string FechaEmision { get; set; }
        public string IdTipoIngreso { get; set; }
        public Nullable<int> IdTipoModalidadOtorgado { get; set; }
        public string ModalidadOtorgado { get; set; }
        public string DocumentoReferencia { get; set; }
        public Nullable<int> IdTipoCajaChica { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public string SIMBOLO { get; set; }
        public Nullable<decimal> MontoSoles { get; set; }
        public Nullable<decimal> MontoDolares { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<int> ChkDiferenteMoneda { get; set; }
        public Nullable<decimal> MontoPagar { get; set; }
        public Nullable<int> IdTipoMotivoOtorgado { get; set; }
        public string MotivoOtorgado { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> IDCUENTABANCARIA { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public string ContratoCompra { get; set; }
        public string APROBACION { get; set; }
        public string BANCO { get; set; }
        public string NroOperacion { get; set; }
        public string FechaTransferencia { get; set; }
        public string DESCCUENTABANCARIA { get; set; }
        public Nullable<int> COSECHA { get; set; }
        public string IDAPROBACION { get; set; }
    }
}
