//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_ANUAL
    {
        public int IDCIERRE { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> COSECHA { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> USUARIOREGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
    }
}
