//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int IdCliente { get; set; }
        public int IdTipoCliente { get; set; }
        public Nullable<int> IdTipoOrigen { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string DocIdentidad { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string NombreCliente { get; set; }
        public string ApellidoCliente { get; set; }
        public string TelefonoPrincipal { get; set; }
        public string TelefonoAlternativo { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdDistrito { get; set; }
        public string CentroPoblado { get; set; }
        public string Caserio { get; set; }
        public string DireccionContrato { get; set; }
        public string DireccionFactura { get; set; }
        public string ReferenciaFactura { get; set; }
        public string DireccionInstruccion { get; set; }
        public string DireccionMuestra { get; set; }
        public Nullable<int> IdIdioma { get; set; }
        public string NombreLegal { get; set; }
        public string ApellidoLegal { get; set; }
        public string DocIdentidadLegal { get; set; }
        public string TelefonoLegal { get; set; }
        public string CorreoLegal { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string IdExcel { get; set; }
        public Nullable<int> IdLiderComercial { get; set; }
        public string IdZona { get; set; }
        public Nullable<int> CodigoLiderComercial { get; set; }
        public string codCafePractice1 { get; set; }
        public string codCafePractice2 { get; set; }
        public string CadenaCP { get; set; }
        public string FLOID { get; set; }
    }
}
