//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTEINHABILITADO
    {
        public int IdClienteInhabilitado { get; set; }
        public string IdTipoCliente { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string DocIdentidad { get; set; }
        public string RazonSocial { get; set; }
        public string NombreCliente { get; set; }
        public string ApellidoCliente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public string IdEstado { get; set; }
    }
}
