//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTEVENTA_FILE_RESPONSE
    {
        public int IdComprobanteFileResponse { get; set; }
        public int IdComprobanteFile { get; set; }
        public string ProcessReceptionId { get; set; }
        public string IssueDate { get; set; }
        public string IssueTime { get; set; }
        public string ResponseDate { get; set; }
        public string ResponseTime { get; set; }
        public string ResponseNote { get; set; }
        public string SenderParty_RUC { get; set; }
        public string ReceiverParty_RUC { get; set; }
        public string RecipientParty_RUC { get; set; }
        public string ResponseCode { get; set; }
        public string DocumentSentId { get; set; }
        public string ProcessedDocumentId { get; set; }
        public string ResponseDescription { get; set; }
        public string SignatureValue { get; set; }
        public string DigestValue { get; set; }
        public string ResponseFileName { get; set; }
        public string ResponseTicket { get; set; }
        public string ResponseStatus { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public string Trama { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
