//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE_VENTA_CAB
    {
        public int IdComprobante { get; set; }
        public string Correlativo { get; set; }
        public string IdLocal { get; set; }
        public string IdTipoComprobante { get; set; }
        public string IdSerieComprobante { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string RazonSocial { get; set; }
        public string DireccionCliente { get; set; }
        public Nullable<int> IdTipoDocumentoCliente { get; set; }
        public string NroDocumentoCliente { get; set; }
        public string Correo { get; set; }
        public string ContratoReferencia { get; set; }
        public string Observaciones { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> ImporteSubtotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string CodigoHash { get; set; }
        public string EstadoEnvioCorreo { get; set; }
        public Nullable<int> IdComprobanteRef { get; set; }
        public string IdMotivo { get; set; }
        public string MotivoDescripcion { get; set; }
        public string PuertoEmbarque { get; set; }
        public string PuertoDestino { get; set; }
        public string IdTipoOperacion { get; set; }
        public string ExpVapor { get; set; }
        public string ExpFormaPago { get; set; }
        public string ExpFlete { get; set; }
        public string ExpSeguro { get; set; }
        public string ExpNotificar { get; set; }
        public string ExpPaisOrigen { get; set; }
        public string ExpOtrosConceptos { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdEstadoProceso { get; set; }
        public Nullable<int> IdComprobanteInterno { get; set; }
        public Nullable<int> IdCatalogoCuentaContable { get; set; }
        public string IdTipoComprobanteRef { get; set; }
        public string CorrelativoRef { get; set; }
        public Nullable<System.DateTime> FechaDocumentoRef { get; set; }
        public string TipoOperacion { get; set; }
    }
}
