//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE_VENTA_DET
    {
        public int IdDetalleComprobante { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public string Unidad { get; set; }
        public string GuiaRemisionRef { get; set; }
        public string DescripcionServicio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string IdTipoImpuesto { get; set; }
        public string IdMotivoServicio { get; set; }
        public Nullable<decimal> ExpCantidadComercial { get; set; }
        public Nullable<decimal> ExpNetWeight { get; set; }
        public Nullable<decimal> ExpTara { get; set; }
        public Nullable<decimal> ExpGrossWeight { get; set; }
        public string ExpMarks { get; set; }
        public string ExpPartidaArancelaria { get; set; }
        public Nullable<decimal> ExpPrecioFairTrade { get; set; }
        public Nullable<decimal> ExpFairTrade { get; set; }
        public Nullable<decimal> ExpPrecioUnitario { get; set; }
        public Nullable<decimal> ExpImporte { get; set; }
        public string ExpMedida { get; set; }
        public Nullable<decimal> ExpMedidaCantidad { get; set; }
        public Nullable<decimal> KgmSaco { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
