//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_ZONA_UNFIXED
    {
        public int IdDetalleSinFijar { get; set; }
        public int IdContrato { get; set; }
        public decimal KgBase { get; set; }
        public int IdMoneda { get; set; }
        public decimal Precio { get; set; }
        public decimal KgFijado { get; set; }
        public decimal Diferencial { get; set; }
        public int IdTipoDiferencial { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdDetalleSwitch { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> UsuarioAprueba { get; set; }
        public Nullable<System.DateTime> FechaAprueba { get; set; }
        public Nullable<int> IdAprobRecha { get; set; }
        public Nullable<int> inVigente { get; set; }
    }
}
