//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_COMPRA_ZONA
    {
        public int IdContrato { get; set; }
        public string IdContratoCompra { get; set; }
        public int IdLocal { get; set; }
        public int IdTipoPrecio { get; set; }
        public Nullable<decimal> TC { get; set; }
        public int IdTipoCompra { get; set; }
        public int Cosecha { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public int IdTipoCafe { get; set; }
        public decimal KgContrato { get; set; }
        public int SacoContrato { get; set; }
        public int IdCliente { get; set; }
        public int IdCalidad { get; set; }
        public Nullable<int> IdRendimiento { get; set; }
        public Nullable<int> IdDefecto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaEntregaI { get; set; }
        public Nullable<System.DateTime> FechaEntregaF { get; set; }
        public int IdOficinaEntrega { get; set; }
        public string IdCertificacion { get; set; }
        public string Certificacion { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<decimal> KgBaseOut { get; set; }
        public Nullable<int> IdMonedaOut { get; set; }
        public Nullable<decimal> PrecioOut { get; set; }
        public Nullable<decimal> KgBaseNuevoOut { get; set; }
        public Nullable<int> IdMonedaNuevoOut { get; set; }
        public Nullable<decimal> PrecioNuevoOut { get; set; }
        public Nullable<int> IdTraderOut { get; set; }
        public Nullable<int> IdAprobacionOut { get; set; }
        public Nullable<decimal> KgBaseUnfix { get; set; }
        public Nullable<int> IdMonedaUnfix { get; set; }
        public Nullable<decimal> PrecioVigenteUnfix { get; set; }
        public Nullable<decimal> KgFijadosVigenteUnfix { get; set; }
        public Nullable<int> IdMesFijacionUnfix { get; set; }
        public Nullable<decimal> DiferencialUnfix { get; set; }
        public Nullable<int> IdTipoDiferencialUnfix { get; set; }
        public Nullable<int> IdUnidadPrecio { get; set; }
        public Nullable<decimal> KgPorSaco { get; set; }
        public Nullable<int> NumSaco { get; set; }
        public Nullable<int> IdContratoReferencia { get; set; }
        public Nullable<decimal> PrecioOutOtorgado { get; set; }
    }
}
