//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREO
    {
        public int IdCorreo { get; set; }
        public string Modulo { get; set; }
        public string Correo1 { get; set; }
        public int IdEstado { get; set; }
    }
}
