//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_BANCO
    {
        public int IdCuentaBanco { get; set; }
        public string NroCuentaBanco { get; set; }
        public string CodigoInterbancario { get; set; }
        public string Descripcion { get; set; }
        public string IdLocal { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
