//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string IdEmpresa { get; set; }
        public string vRazonSocial { get; set; }
        public string vCodigoTributario { get; set; }
        public string vDireccion { get; set; }
        public string vNombreComercial { get; set; }
        public int nEstado { get; set; }
        public string IdUbigeo { get; set; }
        public string IdEmpresaSAP { get; set; }
        public string idSociedadSAP { get; set; }
    }
}
