//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTO_MOVILIDAD_DET
    {
        public int IdMovilidadDet { get; set; }
        public Nullable<int> IdMovilidadCab { get; set; }
        public Nullable<int> IdGastoCentroCosto { get; set; }
        public Nullable<int> IdCatalogoCuentaContable { get; set; }
        public Nullable<System.DateTime> FechaUso { get; set; }
        public Nullable<int> FlagFechaMonto { get; set; }
        public string IdMoneda { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> BaseImponible { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Exceso { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
    }
}
