//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jefatura
    {
        public string IdJefatura { get; set; }
        public string vDescripcion { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> bEstado { get; set; }
        public int nIdUsuario_Mod { get; set; }
        public System.DateTime dFecha_Mod { get; set; }
    }
}
