//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    
    public partial class LisDatosGeneraCodigoBarra
    {
        public string NroDocumentoEmisor { get; set; }
        public string TipoDocumento { get; set; }
        public string NroComprobante { get; set; }
        public Nullable<decimal> TotalIgv { get; set; }
        public Nullable<decimal> TotalVenta { get; set; }
        public string FechaEmision { get; set; }
        public Nullable<int> TipoDocumentoReceptor { get; set; }
        public string NroDocumentoReceptor { get; set; }
        public string DigestValue { get; set; }
        public string SignatureValue { get; set; }
    }
}
