//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA_DET
    {
        public int IdDetalleOrden { get; set; }
        public int IdOrden { get; set; }
        public int inCantidad { get; set; }
        public string vcUnidadMedida { get; set; }
        public string vcDescripcion { get; set; }
        public string TipoModena { get; set; }
        public decimal dcPrecioUnidad { get; set; }
        public decimal dcSubtotal { get; set; }
        public decimal dcTotalDesc { get; set; }
        public decimal dcTotal { get; set; }
        public int inEstado { get; set; }
        public int UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
