//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_COMPRA_CLIENTE_TEMP
    {
        public int ID { get; set; }
        public Nullable<int> IDCONTRATO { get; set; }
        public Nullable<int> IDLOCAL { get; set; }
        public Nullable<int> COSECHA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string OPERACION { get; set; }
        public string TIPOCAFE { get; set; }
        public Nullable<decimal> KGCONTRATO { get; set; }
        public Nullable<int> SACOCONTRATO { get; set; }
        public Nullable<decimal> KGLIQUIDADO { get; set; }
        public Nullable<decimal> PRECIO_SOLES { get; set; }
        public Nullable<decimal> PRECIO_DOLARES { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    }
}
