//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    
    public partial class SelLocalIdEmpresaUsuario
    {
        public string idLocal { get; set; }
        public string vDescripcion { get; set; }
        public string vDireccion { get; set; }
        public string IdEmpresa { get; set; }
        public Nullable<int> nEstado { get; set; }
    }
}
