//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    
    public partial class SelMenuConstruir
    {
        public int IdUsuario { get; set; }
        public string IdMenu { get; set; }
        public string idMenuPadre { get; set; }
        public int IdSistema { get; set; }
        public string vDescripcion { get; set; }
        public string vNombreFormulario { get; set; }
    }
}
