//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_PRP_RESULTADO
    {
        public int IdResultado { get; set; }
        public int IdOrdenServicio { get; set; }
        public int IdTipoOperacion { get; set; }
        public int IdCalidad { get; set; }
        public decimal Rendimiento { get; set; }
        public int IdTipoCafe { get; set; }
        public int IdTipoSaco { get; set; }
        public Nullable<int> NroSaco { get; set; }
        public Nullable<decimal> KgBruto { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public Nullable<decimal> KgNeto { get; set; }
        public Nullable<int> IdGuiaIngreso { get; set; }
        public Nullable<int> Lote { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Certificado { get; set; }
        public int ChkLiquidacion { get; set; }
        public int IdTransito { get; set; }
        public int IdProceso { get; set; }
        public string IdCertificado { get; set; }
        public Nullable<int> IdTipoRuma { get; set; }
        public Nullable<int> inMascaraClie { get; set; }
        public Nullable<int> inValidado { get; set; }
        public Nullable<int> inUsuarioValida { get; set; }
        public Nullable<System.DateTime> dtFechaValida { get; set; }
    }
}
