//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApplicationDbContextSGU : DbContext
    {
        public ApplicationDbContextSGU()
            : base("name=ApplicationDbContextSGU")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Jefatura> Jefatura { get; set; }
        public virtual DbSet<JefaturaCorreo> JefaturaCorreo { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<NotCheckConnect> NotCheckConnect { get; set; }
        public virtual DbSet<Opciones> Opciones { get; set; }
        public virtual DbSet<OpcionMenu> OpcionMenu { get; set; }
        public virtual DbSet<PermitsConnection> PermitsConnection { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolMenu> RolMenu { get; set; }
        public virtual DbSet<Sistemas> Sistemas { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioEmpresa> UsuarioEmpresa { get; set; }
        public virtual DbSet<UsuarioEstacion> UsuarioEstacion { get; set; }
    
        public virtual ObjectResult<SelLocalIdEmpresaUsuario> usp_SelLocalIdEmpresaUsuario(string idEmpresa, Nullable<int> idUsuario)
        {
            var idEmpresaParameter = idEmpresa != null ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelLocalIdEmpresaUsuario>("usp_SelLocalIdEmpresaUsuario", idEmpresaParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SelMenuConstruir> usp_SelMenuConstruir(Nullable<int> idUsuario, Nullable<int> idSistema)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idSistemaParameter = idSistema.HasValue ?
                new ObjectParameter("IdSistema", idSistema) :
                new ObjectParameter("IdSistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelMenuConstruir>("usp_SelMenuConstruir", idUsuarioParameter, idSistemaParameter);
        }
    
        public virtual ObjectResult<Usuario> usp_SelUsuarioLogin(string vUsuario, string vpassword, Nullable<int> nIdSistema)
        {
            var vUsuarioParameter = vUsuario != null ?
                new ObjectParameter("vUsuario", vUsuario) :
                new ObjectParameter("vUsuario", typeof(string));
    
            var vpasswordParameter = vpassword != null ?
                new ObjectParameter("vpassword", vpassword) :
                new ObjectParameter("vpassword", typeof(string));
    
            var nIdSistemaParameter = nIdSistema.HasValue ?
                new ObjectParameter("nIdSistema", nIdSistema) :
                new ObjectParameter("nIdSistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("usp_SelUsuarioLogin", vUsuarioParameter, vpasswordParameter, nIdSistemaParameter);
        }
    
        public virtual ObjectResult<Usuario> usp_SelUsuarioLogin(string vUsuario, string vpassword, Nullable<int> nIdSistema, MergeOption mergeOption)
        {
            var vUsuarioParameter = vUsuario != null ?
                new ObjectParameter("vUsuario", vUsuario) :
                new ObjectParameter("vUsuario", typeof(string));
    
            var vpasswordParameter = vpassword != null ?
                new ObjectParameter("vpassword", vpassword) :
                new ObjectParameter("vpassword", typeof(string));
    
            var nIdSistemaParameter = nIdSistema.HasValue ?
                new ObjectParameter("nIdSistema", nIdSistema) :
                new ObjectParameter("nIdSistema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("usp_SelUsuarioLogin", mergeOption, vUsuarioParameter, vpasswordParameter, nIdSistemaParameter);
        }
    }
}
