//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistemas
    {
        public int IdSistema { get; set; }
        public string vNombre { get; set; }
        public string vDescripcion { get; set; }
        public Nullable<int> nEstado { get; set; }
        public Nullable<bool> bOperacion { get; set; }
        public string vResumen { get; set; }
        public string vUrl { get; set; }
        public string vImagen { get; set; }
        public Nullable<int> nTipo { get; set; }
        public Nullable<bool> bPortal { get; set; }
        public Nullable<bool> bAdmin { get; set; }
    }
}
