//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_BLACKLIST
    {
        public int IdBlackList { get; set; }
        public string NombreTabla { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdEstado { get; set; }
    }
}
