//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_SALDO
    {
        public int IdTrasladoSaldo { get; set; }
        public int IdTraslado { get; set; }
        public Nullable<int> IdGuia { get; set; }
        public int Cosecha { get; set; }
        public decimal KgNeto { get; set; }
        public decimal Operacion { get; set; }
        public decimal Saldo { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdResultado { get; set; }
        public Nullable<int> IdMerma { get; set; }
        public Nullable<int> IdTipoMerma { get; set; }
        public Nullable<int> IdTrasladoDetalle { get; set; }
    }
}
