//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_EMPRESA
    {
        public int IdEmpresaTransporte { get; set; }
        public string IdLocal { get; set; }
        public string DocumentoIdentidad { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public int IdEstado { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> BlackList { get; set; }
        public string UsuarioBL { get; set; }
        public Nullable<System.DateTime> FechaBL { get; set; }
        public string Comentario { get; set; }
    }
}
