//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_DESPACHOCAFE
    {
        public int IdDespachoCafe { get; set; }
        public Nullable<int> IdTraslado { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
        public string HoraLlegada { get; set; }
        public string GeoUrl { get; set; }
        public string UsuarioGeo { get; set; }
        public string ContrasenaGeo { get; set; }
        public string NroMovilConductor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
    }
}
