//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_DET
    {
        public int IdDetalle { get; set; }
        public int IdTraslado { get; set; }
        public int IdGuia { get; set; }
        public string Lote { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> NroFila { get; set; }
        public string Certificado { get; set; }
        public decimal GiKgBruto { get; set; }
        public decimal GiTara { get; set; }
        public decimal GiKgNeto { get; set; }
        public int GiSaco { get; set; }
        public decimal GiRendimiento { get; set; }
        public decimal GiHumedad { get; set; }
        public Nullable<decimal> GrKgBruto { get; set; }
        public Nullable<decimal> GrTara { get; set; }
        public Nullable<decimal> GrKgNeto { get; set; }
        public Nullable<int> GrSaco { get; set; }
        public Nullable<decimal> GrRendimiento { get; set; }
        public Nullable<decimal> GrHumedad { get; set; }
        public Nullable<int> GuiaSaco { get; set; }
        public Nullable<decimal> GuiaKgBruto { get; set; }
        public Nullable<decimal> GuiaTara { get; set; }
        public Nullable<decimal> GuiaKgNeto { get; set; }
        public int IdEstado { get; set; }
        public Nullable<decimal> GrPromRendimiento { get; set; }
        public Nullable<decimal> GrPromHumedad { get; set; }
        public string IdCertificado { get; set; }
    }
}
