//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubigeo
    {
        public string IdUbigeo { get; set; }
        public string vDepartamento { get; set; }
        public string vProvincia { get; set; }
        public string vDistrito { get; set; }
        public int nEstado { get; set; }
    }
}
